on:
  workflow_call

jobs:
  Comment_pr:
    runs-on: ubuntu-latest
    name: Pull Request comment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello and welcome :wave:
            You have now opend up a PR 

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}